# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [17]:
import numpy as np
arr = np.loadtxt("minutes_n_ingredients.csv",
                 delimiter=",", skiprows = 1, dtype=np.int32)
str1 = arr[:5,:]
str1

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [19]:
data_1 = arr[:,1:]
means = np.mean(data_1, axis = 0)
mins = np.min(data_1, axis = 0)
maxs = np.max(data_1, axis = 0)
medians = np.median(data_1, axis = 0)

print("Means: ", means)
print("Mins: ", mins)
print("Maxs: ", maxs)
print("Medians: ", medians)

Means:  [2.16010017e+04 9.05528000e+00]
Mins:  [0 1]
Maxs:  [2147483647         39]
Medians:  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [23]:
arr[:, 1] = np.clip(arr[:, 1], 0, np.quantile(arr[:, 1], 0.75))
print(arr)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [35]:
print(len(arr[arr[:, 1] == 0]))
arr[arr[:, 1] == 0] = 1

0


In [36]:
print(len(arr[arr[:, 1] == 0]))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [37]:
len(np.unique(arr[:, 0]))

99522

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [38]:
ingr = set(arr[:, 2])
print(len(ingr))

37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [39]:
under_data = np.copy(arr)
mask = (under_data[:, 2] <= 5)
under_data[mask, :]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [40]:
cost = arr[:, 2] / arr[:, 1]
print(cost.max(axis = 0))

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [41]:
data_sort = arr[arr[:, 1].argsort()]
data_sort = data_sort[-100:]
np.mean(data_sort[:, 2])

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [42]:
lst = np.random.randint(0, 100000, size = (1, 10))
print(arr[lst])

[[[242032     65      3]
  [225937     25      8]
  [ 38826     10      8]
  [244642     65     12]
  [ 44729     55      6]
  [378458      7      4]
  [371012     20      9]
  [514925     40      5]
  [315153      2      6]
  [ 77906     45      9]]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [43]:
percent = (arr[:, 2] <= np.mean(arr[:, 2]))
len(arr[percent, :])/len(arr)*100  

58.989000000000004

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [44]:
simple_data = np.copy(arr)
cost =[1 if line[1] <= 20 and line[2] <= 5 else 0 for line in simple_data]
simple_data = np.insert(simple_data, 3, values = cost, axis = 1)
simple_data

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.